all: CONSTANTException.class cCONSTANTMgr.class cCONSTANTPool.class\
     cCONSTANT_Class_Info.class cCONSTANT_Double_Info.class\
     cCONSTANT_Float_Info.class cCONSTANT_Integer_Info.class\
     cCONSTANT_Long_Info.class cCONSTANT_NameAndType_Info.class\
     cCONSTANT_Ref_Info.class cCONSTANT_String_Info.class\
     cCONSTANT_Utf8_Info.class

CONSTANTException.class: CONSTANTException.java
	$(JAVACOMPILER) CONSTANTException.java

cCONSTANTMgr.class: cCONSTANTMgr.java
	$(JAVACOMPILER) cCONSTANTMgr.java

cCONSTANTPool.class: cCONSTANTPool.java
	$(JAVACOMPILER) cCONSTANTPool.java

cCONSTANT_Class_Info.class: cCONSTANT_Class_Info.java
	$(JAVACOMPILER) cCONSTANT_Class_Info.java

cCONSTANT_Double_Info.class: cCONSTANT_Double_Info.java
	$(JAVACOMPILER) cCONSTANT_Double_Info.java

cCONSTANT_Float_Info.class: cCONSTANT_Float_Info.java
	$(JAVACOMPILER) cCONSTANT_Float_Info.java

cCONSTANT_Integer_Info.class: cCONSTANT_Integer_Info.java
	$(JAVACOMPILER) cCONSTANT_Integer_Info.java

cCONSTANT_Long_Info.class: cCONSTANT_Long_Info.java
	$(JAVACOMPILER) cCONSTANT_Long_Info.java

cCONSTANT_NameAndType_Info.class: cCONSTANT_NameAndType_Info.java
	$(JAVACOMPILER) cCONSTANT_NameAndType_Info.java

cCONSTANT_Ref_Info.class: cCONSTANT_Ref_Info.java
	$(JAVACOMPILER) cCONSTANT_Ref_Info.java

cCONSTANT_String_Info.class: cCONSTANT_String_Info.java
	$(JAVACOMPILER) cCONSTANT_String_Info.java

cCONSTANT_Utf8_Info.class: cCONSTANT_Utf8_Info.java
	$(JAVACOMPILER) cCONSTANT_Utf8_Info.java

clean:
	rm -f CONSTANTException.class cCONSTANTMgr.class cCONSTANTPool.class
	rm -f cCONSTANT_Class_Info.class cCONSTANT_Double_Info.class
	rm -f cCONSTANT_Float_Info.class cCONSTANT_Integer_Info.class
	rm -f cCONSTANT_Long_Info.class cCONSTANT_NameAndType_Info.class
	rm -f cCONSTANT_Ref_Info.class cCONSTANT_String_Info.class
	rm -f cCONSTANT_Utf8_Info.class

